#!/usr/bin/env bash
# deploy-audit.sh — doc 17 inspect mode (scorecard + top-5)
set -euo pipefail

usage() {
  cat <<'EOF'
deploy-audit.sh — inspect a deployment target and emit a scorecard

WHAT IT DOES
  Collects what it can without special access (HTTP headers, basic Lighthouse
  if installed, optional Vercel API metrics when VERCEL_TOKEN is set) and writes
  reports/deploy-audit-<date>.md with a scorecard shell and top-5 optimization
  slots for an agent to complete with judgment.

WHY
  Doc 17: measure before optimize; adoption needs baseline budgets for UX-eval.

RISKS
  - Network calls to the live URL.
  - VERCEL_TOKEN grants project read — use a scoped token; never commit it.
  - Partial data when APIs unavailable (report marks gaps honestly).

USAGE
  deploy-audit.sh --url <https://...> [--root <repo>] [--vercel-project ID]
  deploy-audit.sh --help

EXAMPLES
  ./scripts/deploy-audit.sh --url https://acme.vercel.app --root ~/Code/acme-app
  VERCEL_TOKEN=… ./scripts/deploy-audit.sh --url https://acme.com --vercel-project prj_xxx
EOF
}

URL=""
ROOT="."
VPROJ=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help) usage; exit 0 ;;
    --url) URL="$2"; shift 2 ;;
    --root) ROOT="$2"; shift 2 ;;
    --vercel-project) VPROJ="$2"; shift 2 ;;
    *) echo "unknown: $1" >&2; usage; exit 2 ;;
  esac
done

[[ -n "$URL" ]] || { usage; exit 2; }

DATE=$(date -u +"%Y-%m-%d")
OUTDIR="$ROOT/reports"
mkdir -p "$OUTDIR"
OUT="$OUTDIR/deploy-audit-${DATE}.md"

info() { echo "deploy-audit: $*" >&2; }

# Headers sample
HDR=$(mktemp)
curl -sS -D "$HDR" -o /dev/null --max-time 30 "$URL" || true
CACHE=$(tr -d '\r' < "$HDR" | grep -i '^cache-control:' || echo "cache-control: (missing)")
CSP=$(tr -d '\r' < "$HDR" | grep -i '^content-security-policy:' || echo "csp: (missing)")
rm -f "$HDR"

# Optional Lighthouse JSON summary
LH_SUMMARY="(lighthouse not installed or failed)"
if command -v npx >/dev/null && command -v node >/dev/null 2>&1; then
  LH_TMP=$(mktemp)
  if npx --yes lighthouse@"11" "$URL" --quiet --chrome-flags="--headless --no-sandbox" \
      --only-categories=performance,accessibility,seo --output=json --output-path="$LH_TMP" 2>/dev/null; then
    LH_SUMMARY=$(node -e '
      const j=require(process.argv[1]);
      const c=j.categories||{};
      const a=j.audits||{};
      const n=id=> (a[id]&&a[id].numericValue!=null)?Math.round(a[id].numericValue):"?";
      console.log(`perf=${(c.performance&&c.performance.score)!=null?c.performance.score:"?"} a11y=${(c.accessibility&&c.accessibility.score)!=null?c.accessibility.score:"?"} seo=${(c.seo&&c.seo.score)!=null?c.seo.score:"?"} LCP_ms=${n("largest-contentful-paint")} CLS=${(a["cumulative-layout-shift"]&&a["cumulative-layout-shift"].displayValue)||"?"}`);
    ' "$LH_TMP" 2>/dev/null || echo "(parse failed)")
  fi
  rm -f "$LH_TMP"
fi

# Optional Vercel
VERCEL_BLOCK="(set VERCEL_TOKEN + --vercel-project for API metrics)"
if [[ -n "${VERCEL_TOKEN:-}" && -n "$VPROJ" ]] && command -v node >/dev/null 2>&1; then
  VERCEL_BLOCK=$(curl -sS --max-time 20 -H "Authorization: Bearer $VERCEL_TOKEN" \
    "https://api.vercel.com/v9/projects/${VPROJ}" 2>/dev/null \
    | node -e 'let d="";process.stdin.on("data",c=>d+=c);process.stdin.on("end",()=>{try{const j=JSON.parse(d);console.log("project="+j.name+" framework="+(j.framework||"?"));}catch(e){console.log("(vercel parse failed)")}})' \
    || echo "(vercel API failed)")
elif [[ -n "${VERCEL_TOKEN:-}" && -n "$VPROJ" ]]; then
  VERCEL_BLOCK="(node not on PATH — cannot parse Vercel API JSON)"
fi

# Posture reuse
POSTURE="(run posture-probe.sh separately)"
if [[ -x "$(dirname "$0")/posture-probe.sh" ]]; then
  if "$(dirname "$0")/posture-probe.sh" "$URL" --no-burst >/tmp/posture-out 2>&1; then
    POSTURE="pass — see posture-probe"
  else
    POSTURE="fail or partial — $(tail -n 3 /tmp/posture-out | tr '\n' ' ')"
  fi
fi

cat > "$OUT" <<EOF
# Deploy audit — $DATE

**URL:** $URL  
**Generated by:** scripts/deploy-audit.sh (docs/17 inspect)  
**Repo root:** $ROOT

## Scorecard

| Section | Grade (A–F) | Evidence |
|---|---|---|
| 1 Rendering & delivery | _TBD agent_ | Cache: \`$CACHE\` |
| 2 Field performance | _TBD_ | Lab Lighthouse: \`$LH_SUMMARY\` (field vitals need Speed Insights) |
| 3 Compute & cost | _TBD_ | Vercel: $VERCEL_BLOCK |
| 4 Reliability | _TBD_ | _pull runtime logs / error rates_ |
| 5 Discovery & correctness | _TBD_ | _SEO/AEO + broken link pass_ |
| 6 Posture | _see probe_ | $POSTURE |

## Top 5 optimizations (impact ÷ effort)

Fill after agent judgment; each needs metric + expected delta + measurement method.

1. _…_
2. _…_
3. _…_
4. _…_
5. _…_

## Issues to file

Use docs/04 contracts; tag \`optimization\`. Sprint contract = before/after measurement.

## Operator translation

> Your site was checked at $URL on $DATE. Lab snapshot: $LH_SUMMARY.
> A teammate will turn the top fixes into plain language next.

## Gaps / honesty

- Field Web Vitals require Vercel Analytics / CrUX — not invented here.
- Bundle analysis requires running the app's analyzer in CI.
- This script seeds the report; the **monitor/historian** completes grades.

EOF

info "wrote $OUT"
echo "$OUT"
